version: '3'
services:
  frontend:
    container_name: camagru_front
    env_file:
      - .env
    image: nginx:alpine
    ports:
      - '3000:80'
    volumes:
      - ./front/src:/usr/share/nginx/html
    networks:
      - camagru-network

  backend:
    container_name: camagru_backend
    build:
      context: ./back
      dockerfile: dockerfile
    image: camagru_back_image
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - ./back:/app
    networks:
      - camagru-network

  db:
    container_name: db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - camagru-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
    networks:
      - camagru-network

volumes:
  postgres:
    name: postgres-volume

networks:
  camagru-network:
